import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import cn from "classnames";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

import { api, type RouterOutputs } from "~/utils/api";

dayjs.extend(relativeTime);

const Home: NextPage = () => {
  const { data: posts } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Trash Posting</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cn(
          "bg-gradient-to-b from-[#111827] to-[#030712] text-white"
        )}
      >
        <div
          className={cn(
            "flex h-screen flex-col items-center justify-center overflow-y-scroll  border-x border-white ",
            "mx-auto w-full  md:w-[720px]"
          )}
        >
          {posts?.map((post) => (
            <PostView key={post.post.id} postData={post} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

type PostData = RouterOutputs["posts"]["getAll"][number];

const PostView = ({ postData }: { postData: PostData }) => {
  return (
    <div className="flex w-full gap-x-5 border-b border-white p-5">
      <div className="relative col-span-1 h-[64px] w-[64px] ">
        <Image
          alt={`@${postData.author.userName} avatar`}
          src={postData.author.profileImageUrl}
          fill
          className="rounded-full"
        />
      </div>
      <div className="col-span-3">
        <div className="font-sm flex gap-x-1 text-gray-300">
          <span>@{postData.author.userName}</span>
          <span>{`· ${dayjs(postData.post.createdAt).fromNow()}`}</span>
        </div>
        <div className="mt-1 flex text-lg">{postData.post.content}</div>
      </div>
    </div>
  );
};

const CreatePost = () => {
  const user = useUser();
  return <></>;
};
